<a href="https://colab.research.google.com/github/sabill/dphi-boothcamp-ml/blob/main/module_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(L)

In [ ]:
arr.sort()

In [ ]:
arr

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [ ]:
np.append(arr, 53).reshape(2,7)

array([[ 2,  3,  7,  8, 10, 12, 13],
       [22, 23, 25, 41, 46, 54, 53]])

In [ ]:
arr2 = np.array(range(25))
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr2 = arr2.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[0:2, -2:]

array([[3, 4],
       [8, 9]])

In [ ]:
arr2[1:5:2,0:5:2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [1]:
import pandas as pd

In [2]:
sma_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Standard_Metropolitan_Areas_Data-data.csv")

In [3]:
sma_data.shape

(99, 10)

In [4]:
sma_data.tail()

land_area  percent_city  percent_senior  ...  income  region  crime_rate
94       1511          38.7            10.7  ...    1452       4       70.66
95       1543          39.6             8.1  ...     769       3       36.36
96       1011          37.8            10.5  ...    1337       3       60.16
97        813          13.4            10.9  ...    1589       1       36.33
98        654          28.8             3.9  ...    1148       3       68.76

[5 rows x 10 columns]

In [9]:
sma_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   land_area       99 non-null     int64  
 1   percent_city    99 non-null     float64
 2   percent_senior  99 non-null     float64
 3   physicians      99 non-null     int64  
 4   hospital_beds   99 non-null     int64  
 5   graduates       99 non-null     float64
 6   work_force      99 non-null     float64
 7   income          99 non-null     int64  
 8   region          99 non-null     int64  
 9   crime_rate      99 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 7.9 KB
