<a href="https://colab.research.google.com/github/sabill/dphi-boothcamp-ml/blob/main/module_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(L)

In [ ]:
arr.sort()

In [ ]:
arr

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [ ]:
np.append(arr, 53).reshape(2,7)

array([[ 2,  3,  7,  8, 10, 12, 13],
       [22, 23, 25, 41, 46, 54, 53]])

In [ ]:
arr2 = np.array(range(25))
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr2 = arr2.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[0:2, -2:]

array([[3, 4],
       [8, 9]])

In [ ]:
arr2[1:5:2,0:5:2]

array([[ 5,  7,  9],
       [15, 17, 19]])