<a href="https://colab.research.google.com/github/sabill/dphi-boothcamp-ml/blob/main/module_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [ ]:
import numpy as np

In [ ]:
arr = np.array(L)

In [ ]:
arr.sort()

In [ ]:
arr

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [ ]:
np.append(arr, 53).reshape(2,7)

array([[ 2,  3,  7,  8, 10, 12, 13],
       [22, 23, 25, 41, 46, 54, 53]])

In [ ]:
arr2 = np.array(range(25))
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr2 = arr2.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[0:2, -2:]

array([[3, 4],
       [8, 9]])

In [ ]:
arr2[1:5:2,0:5:2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [24]:
import pandas as pd

In [25]:
sma_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Standard_Metropolitan_Areas_Data-data.csv")

In [12]:
sma_data.shape

(99, 10)

In [13]:
sma_data.tail()

land_area  percent_city  percent_senior  ...  income  region  crime_rate
94       1511          38.7            10.7  ...    1452       4       70.66
95       1543          39.6             8.1  ...     769       3       36.36
96       1011          37.8            10.5  ...    1337       3       60.16
97        813          13.4            10.9  ...    1589       1       36.33
98        654          28.8             3.9  ...    1148       3       68.76

[5 rows x 10 columns]

In [14]:
sma_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   land_area       99 non-null     int64  
 1   percent_city    99 non-null     float64
 2   percent_senior  99 non-null     float64
 3   physicians      99 non-null     int64  
 4   hospital_beds   99 non-null     int64  
 5   graduates       99 non-null     float64
 6   work_force      99 non-null     float64
 7   income          99 non-null     int64  
 8   region          99 non-null     int64  
 9   crime_rate      99 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 7.9 KB


##Indexing, selecting, assigning

In [15]:
sma_data.iloc[10]

land_area          1008.00
percent_city         16.60
percent_senior       10.30
physicians         4006.00
hospital_beds     16704.00
graduates            55.90
work_force          935.50
income            15953.00
region                1.00
crime_rate           54.16
Name: 10, dtype: float64

In [17]:
sma_data.physicians.iloc[-1]

140

In [19]:
sample_data1 = sma_data.loc[[1,3,5,7,9,13], ['land_area', 'work_force', 'income', 'region','crime_rate']]

In [20]:
sample_data1

land_area  work_force  income  region  crime_rate
1        3719      3305.9   54542       2       56.03
3        3916      1966.7   32906       2       67.38
5        2815      1541.9   25663       3       58.48
7        6794      1272.7   18221       3       64.88
9        4647      1032.2   14542       2       55.30
13        782       915.2   12591       4       63.20

In [21]:
sample_data2 = sma_data[sma_data.region==2]

In [23]:
sample_data2.count()

land_area         25
percent_city      25
percent_senior    25
physicians        25
hospital_beds     25
graduates         25
work_force        25
income            25
region            25
crime_rate        25
dtype: int64

In [26]:
sma_data.mean()

land_area         2615.727273
percent_city        42.518182
percent_senior       9.781818
physicians        1828.333333
hospital_beds     6345.868687
graduates           54.463636
work_force         449.366667
income            6762.505051
region               2.494949
crime_rate          55.643030
dtype: float64

In [28]:
sma_data.region.nunique()

4

In [30]:
sma_data.describe()

land_area  percent_city  ...     region  crime_rate
count     99.000000     99.000000  ...  99.000000   99.000000
mean    2615.727273     42.518182  ...   2.494949   55.643030
std     3045.826210     17.348277  ...   1.013921   13.470943
min       47.000000     13.400000  ...   1.000000   23.320000
25%     1408.000000     30.100000  ...   2.000000   46.115000
50%     1951.000000     39.500000  ...   3.000000   56.060000
75%     2890.500000     52.600000  ...   3.000000   63.860000
max    27293.000000    100.000000  ...   4.000000   85.620000

[8 rows x 10 columns]

In [31]:
sample_data1 = sma_data[sma_data.region == 3]

In [33]:
sample_data1.describe()

land_area  percent_city  ...  region  crime_rate
count    36.000000     36.000000  ...    36.0   36.000000
mean   2485.972222     46.172222  ...     3.0   58.265556
std    1653.813800     19.101019  ...     0.0   10.155822
min     654.000000     14.500000  ...     3.0   36.360000
25%    1517.000000     31.350000  ...     3.0   52.447500
50%    2018.000000     47.000000  ...     3.0   58.725000
75%    2911.000000     59.725000  ...     3.0   64.922500
max    8360.000000     90.700000  ...     3.0   76.350000

[8 rows x 10 columns]

In [34]:
sample_data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36 entries, 5 to 98
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   land_area       36 non-null     int64  
 1   percent_city    36 non-null     float64
 2   percent_senior  36 non-null     float64
 3   physicians      36 non-null     int64  
 4   hospital_beds   36 non-null     int64  
 5   graduates       36 non-null     float64
 6   work_force      36 non-null     float64
 7   income          36 non-null     int64  
 8   region          36 non-null     int64  
 9   crime_rate      36 non-null     float64
dtypes: float64(5), int64(5)
memory usage: 3.1 KB


In [39]:
sma_data.region.value_counts()

3    36
2    25
1    21
4    17
Name: region, dtype: int64

In [48]:
sorted_data1 = sma_data.sort_values(by='crime_rate', ascending=False)
sorted_data1.head()

land_area  percent_city  percent_senior  ...  income  region  crime_rate
20       9155          53.8            11.1  ...    7766       4       85.62
74       1412          39.2            11.3  ...    2098       4       82.68
53       5966          39.5             9.6  ...    3007       4       80.94
4        2480          31.5            10.5  ...   26573       4       80.19
67       8152          22.3             9.1  ...    2257       4       78.10

[5 rows x 10 columns]

In [60]:
titanic_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/First_ML_Model/master/titanic.csv')
titanic_data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [56]:
titanic_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [57]:
age_mean_before = titanic_data.Age.mean()
print(age_mean_before)
titanic_data.Age.fillna(age_mean_before, inplace=True)

29.69911764705882


In [58]:
age_mean_after = titanic_data.Age.mean()
age_mean_after

29.699117647058763

In [59]:
titanic_data.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [61]:
titanic_data.Embarked.fillna('S', inplace=True)

In [62]:
titanic_data.Embarked.value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64